version: '3'

services:
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tarea1
    ports:
      - "5432:5432"
  
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db

  backend:
    build: backend
    ports:
      - "4000:4000"
    links:
      - db
      - frontend
    depends_on:
      - db
      - frontend